-- Migration to add OAuth fields to User table
ALTER TABLE "elucide-v2"."User"
ADD COLUMN IF NOT EXISTS "name" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "image" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "provider" VARCHAR(64),
ADD COLUMN IF NOT EXISTS "providerAccountId" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP DEFAULT NOW(); 